-- Milestone 3: Task Dependencies & Scheduling
-- Additive migration - does not alter existing data

-- Add duration_days to tasks for CPM scheduling.
-- Defaults to 1 day for all existing rows.
ALTER TABLE tasks
    ADD COLUMN IF NOT EXISTS duration_days INTEGER NOT NULL DEFAULT 1;

-- Dependency type values:
--   FINISH_TO_START  (FS) - successor starts after predecessor finishes  [most common]
--   START_TO_START   (SS) - successor starts after predecessor starts
--   FINISH_TO_FINISH (FF) - successor finishes after predecessor finishes
--   START_TO_FINISH  (SF) - successor finishes after predecessor starts

CREATE TABLE task_dependencies (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id          BIGINT       NOT NULL,
    predecessor_task_id BIGINT       NOT NULL,
    successor_task_id   BIGINT       NOT NULL,
    dependency_type     VARCHAR(30)  NOT NULL DEFAULT 'FINISH_TO_START',
    lag_days            INTEGER      NOT NULL DEFAULT 0,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_td_project      FOREIGN KEY (project_id)          REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_td_predecessor  FOREIGN KEY (predecessor_task_id) REFERENCES tasks(id)    ON DELETE CASCADE,
    CONSTRAINT fk_td_successor    FOREIGN KEY (successor_task_id)   REFERENCES tasks(id)    ON DELETE CASCADE,

    -- A given predecessor→successor pair must be unique (no duplicate edges)
    CONSTRAINT uq_td_pair UNIQUE (predecessor_task_id, successor_task_id)
);

CREATE INDEX idx_td_project_id          ON task_dependencies(project_id);
CREATE INDEX idx_td_predecessor_task_id ON task_dependencies(predecessor_task_id);
CREATE INDEX idx_td_successor_task_id   ON task_dependencies(successor_task_id);
