-- Milestone 4 Schema Additions
-- Team Management, Tracking, and Risk Detection

CREATE TABLE team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(100),
    timezone VARCHAR(50),
    hourly_rate NUMERIC(10,2) CHECK (hourly_rate >= 0),
    availability_hours_per_week NUMERIC(5,2) DEFAULT 40.0 CHECK (availability_hours_per_week >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_team_members_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX idx_team_members_project_id ON team_members(project_id);

CREATE TABLE skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE team_member_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_member_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    proficiency_level VARCHAR(30) NOT NULL, -- BEGINNER, INTERMEDIATE, ADVANCED, EXPERT
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tms_team_member FOREIGN KEY (team_member_id) REFERENCES team_members(id) ON DELETE CASCADE,
    CONSTRAINT fk_tms_skill FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE,
    CONSTRAINT uq_tms_pair UNIQUE (team_member_id, skill_id)
);

CREATE TABLE task_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    team_member_id BIGINT NOT NULL,
    allocation_percentage NUMERIC(5,2) NOT NULL DEFAULT 100.0 CHECK (allocation_percentage >= 0 AND allocation_percentage <= 100),
    planned_hours NUMERIC(8,2) CHECK (planned_hours >= 0),
    actual_hours NUMERIC(8,2) DEFAULT 0 CHECK (actual_hours >= 0),
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ta_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_ta_team_member FOREIGN KEY (team_member_id) REFERENCES team_members(id) ON DELETE CASCADE,
    CONSTRAINT uq_ta_pair UNIQUE (task_id, team_member_id)
);

CREATE INDEX idx_task_assignments_task_id ON task_assignments(task_id);
CREATE INDEX idx_task_assignments_team_member_id ON task_assignments(team_member_id);

CREATE TABLE project_cost_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    task_id BIGINT,
    category VARCHAR(50) NOT NULL, -- LABOR, SOFTWARE, INFRASTRUCTURE, LICENSE, OTHER
    description VARCHAR(500),
    amount NUMERIC(14,2) NOT NULL CHECK (amount >= 0),
    entry_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pce_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_pce_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL
);

CREATE INDEX idx_project_cost_entries_project_id ON project_cost_entries(project_id);

CREATE TABLE project_risks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    risk_type VARCHAR(50) NOT NULL, -- SCHEDULE_DELAY, OVERDUE_TASK, etc.
    severity VARCHAR(30) NOT NULL, -- LOW, MEDIUM, HIGH, CRITICAL
    risk_score INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    evidence_json TEXT,
    suggested_action TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN', -- OPEN, ACKNOWLEDGED, RESOLVED, DISMISSED
    detected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_project_risks_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX idx_project_risks_project_id ON project_risks(project_id);
