-- V4: Sprint Management, Business Calendar Holidays, Integration Configs
-- All tables additive — no modification of existing tables.

-- ─────────────────────────────────────────────────────────────
-- 1. Sprints (Agile Sprint management)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE sprints (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id     BIGINT NOT NULL,
    name           VARCHAR(150) NOT NULL,
    goal           VARCHAR(500),
    start_date     DATE,
    end_date       DATE,
    status         VARCHAR(30)  NOT NULL DEFAULT 'PLANNED', -- PLANNED | ACTIVE | COMPLETED
    velocity_points INTEGER DEFAULT 0,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sprints_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX idx_sprints_project_id ON sprints(project_id);

-- Link tasks to a sprint (optional — null means backlog)
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS sprint_id BIGINT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS story_points INTEGER DEFAULT 0;
ALTER TABLE tasks ADD CONSTRAINT fk_task_sprint
    FOREIGN KEY (sprint_id) REFERENCES sprints(id) ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────
-- 2. Regional Holiday Calendar (business-day CPM engine)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE business_holidays (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   BIGINT,        -- NULL = global holiday
    holiday_date DATE    NOT NULL,
    name         VARCHAR(150),
    region       VARCHAR(50),
    CONSTRAINT fk_bh_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT uq_bh_date_project UNIQUE (project_id, holiday_date)
);

CREATE INDEX idx_business_holidays_date ON business_holidays(holiday_date);

-- ─────────────────────────────────────────────────────────────
-- 3. External Integration Configurations (Jira, GitHub, etc.)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE integration_configs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT NOT NULL,
    provider        VARCHAR(50) NOT NULL, -- JIRA | ASANA | MONDAY | GITHUB | GITLAB | MS_PROJECT
    display_name    VARCHAR(150),
    base_url        VARCHAR(500),
    access_token    TEXT,        -- stored encrypted in production; plain for demo
    refresh_token   TEXT,
    token_expires_at TIMESTAMP,
    config_json     TEXT,        -- provider-specific JSON (repo, board-id, etc.)
    status          VARCHAR(30) NOT NULL DEFAULT 'PENDING', -- PENDING | CONNECTED | ERROR | DISCONNECTED
    last_synced_at  TIMESTAMP,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ic_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT uq_ic_project_provider UNIQUE (project_id, provider)
);

CREATE INDEX idx_integration_configs_project_id ON integration_configs(project_id);

-- ─────────────────────────────────────────────────────────────
-- 4. GitHub/GitLab Webhook Events linked to Tasks
-- ─────────────────────────────────────────────────────────────
CREATE TABLE integration_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integration_id  BIGINT NOT NULL,
    event_type      VARCHAR(50),  -- PR_MERGED | COMMIT | ISSUE_CLOSED | etc.
    external_id     VARCHAR(200), -- PR number / commit SHA
    task_id         BIGINT,       -- linked task (nullable)
    payload_json    TEXT,
    processed_at    TIMESTAMP,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ie_integration FOREIGN KEY (integration_id) REFERENCES integration_configs(id) ON DELETE CASCADE,
    CONSTRAINT fk_ie_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL
);
